version: '3.8'

services:
  bot:
    image: autorundaybot:0.0.4
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - tg_bot:/usr/src/app/tg_bot/data
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot

networks:
  tg_bot:
    driver: bridge

volumes:
  bot:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\test